# 前端docker文件  需要打包好启动
FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY ../zero-nginx-config/nginx-frontend.conf /etc/nginx/conf.d/default.conf