FROM node:18 as build-stage

# 设置工作区域
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY ./frontend .

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./frontend/package*.json ./

# 安装项目依赖
RUN yarn install

# 打包
RUN npm run build

FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY --from=build-stage /app/dist /usr/share/nginx/html
# 有证书
COPY /zero-nginx-config/nginx-frontend-sll.conf /etc/nginx/conf.d/default.conf
COPY ./zero-nginx-config/ssl_certificate/xiaobaicodes.com.key /etc/nginx/xiaobaicodes.com.key
COPY ./zero-nginx-config/ssl_certificate/xiaobaicodes.com.pem /etc/nginx/xiaobaicodes.com.pem
# 没证书
#COPY /zero-nginx-config/nginx-frontend.conf /etc/nginx/conf.d/default.conf;\

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]