FROM python:3.12-slim

WORKDIR /app

COPY ./backend /app

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime


RUN pip install uv -i https://mirrors.aliyun.com/pypi/simple/

RUN uv sync

RUN chmod +x /app/start.sh

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8998

ENTRYPOINT ["/app/start.sh"]

#docker run --restart=always -d --name zerorunner -p 8092:8092 zerorunner
